version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "v2"
    schedule:
      interval: "weekly"
    groups:
      components:
        patterns:
          - "*"

  - package-ecosystem: "gradle"
    directory: "/versions/1.21.1-neoforge"
    target-branch: "v2"
    schedule:
      interval: "weekly"
    groups:
      version-components:
        patterns:
          - "*"
    ignore:
      - dependency-name: "net.fabricmc:fabric-loader"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "gradle"
    directory: "/versions/1.21.11-neoforge"
    target-branch: "v2"
    schedule:
      interval: "weekly"
    groups:
      version-components:
        patterns:
          - "*"

  - package-ecosystem: "gradle"
    directory: "/versions/26.1.2-neoforge"
    target-branch: "v2"
    schedule:
      interval: "weekly"
    groups:
      version-components:
        patterns:
          - "*"

  - package-ecosystem: "gradle"
    directory: "/versions/26.2-neoforge"
    target-branch: "v2"
    schedule:
      interval: "weekly"
    groups:
      version-components:
        patterns:
          - "*"

  - package-ecosystem: "gradle"
    directory: "/versions/1.21.1-fabric"
    target-branch: "v2"
    schedule:
      interval: "weekly"
    groups:
      version-components:
        patterns:
          - "*"

  - package-ecosystem: "gradle"
    directory: "/versions/1.21.11-fabric"
    target-branch: "v2"
    schedule:
      interval: "weekly"
    groups:
      version-components:
        patterns:
          - "*"

  - package-ecosystem: "gradle"
    directory: "/versions/26.1.2-fabric"
    target-branch: "v2"
    schedule:
      interval: "weekly"
    groups:
      version-components:
        patterns:
          - "*"

  - package-ecosystem: "gradle"
    directory: "/versions/26.2-fabric"
    target-branch: "v2"
    schedule:
      interval: "weekly"
    groups:
      version-components:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "v2"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"
