plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.143'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    withSourcesJar()
}

repositories {
    mavenCentral()
}

neoForge {
    version = neo_version

    runs {
        server {
            server()
            programArgument '--nogui'
            systemProperty 'forge.logging.console.level', 'info'
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    jarJar(implementation('org.yaml:snakeyaml:2.6')) {
        version {
            strictly '[2.0,3.0)'
            prefer '2.5'
        }
    }
    additionalRuntimeClasspath 'org.yaml:snakeyaml:2.6'
    jarJar(implementation('org.xerial:sqlite-jdbc:3.50.3.0')) {
        version {
            strictly '[3.45,4.0)'
            prefer '3.50.3.0'
        }
    }
    additionalRuntimeClasspath 'org.xerial:sqlite-jdbc:3.50.3.0'
    jarJar(implementation('com.mysql:mysql-connector-j:9.7.0')) {
        version {
            strictly '[9.0,10.0)'
            prefer '9.7.0'
        }
    }
    additionalRuntimeClasspath 'com.mysql:mysql-connector-j:9.7.0'
    jarJar(implementation('com.google.protobuf:protobuf-java:4.31.1')) {
        version {
            strictly '[4.31,5.0)'
            prefer '4.31.1'
        }
    }
    additionalRuntimeClasspath 'com.google.protobuf:protobuf-java:4.31.1'
    jarJar(implementation('org.mariadb.jdbc:mariadb-java-client:3.5.9')) {
        version {
            strictly '[3.0,4.0)'
            prefer '3.5.9'
        }
    }
    additionalRuntimeClasspath 'org.mariadb.jdbc:mariadb-java-client:3.5.9'

    testImplementation platform('org.junit:junit-bom:6.1.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

def generateModMetadata = tasks.register('generateModMetadata', ProcessResources) {
    def replaceProperties = [
        minecraft_version_range: minecraft_version_range,
        neo_version_range      : neo_version_range,
        loader_version_range   : loader_version_range,
        mod_id                 : mod_id,
        mod_name               : mod_name,
        mod_license            : mod_license,
        mod_version            : mod_version
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from 'src/main/templates'
    into layout.buildDirectory.dir('generated/sources/modMetadata')
}

sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
    options.compilerArgs.add('-Xlint:deprecation')
}

tasks.named('test', Test) {
    useJUnitPlatform()
}

tasks.named('jar', Jar) {
    manifest {
        attributes(
            'Specification-Title': mod_name,
            'Specification-Vendor': 'Baymaxawa',
            'Specification-Version': mod_version,
            'Implementation-Title': project.name,
            'Implementation-Version': mod_version,
            'Implementation-Vendor': 'Baymaxawa'
        )
    }
}
